name: KokoMemo build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
        env:
          DEPLOY_URL: https://kokoseij.github.io/kokomemo-react/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page-url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4

